config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :benefit_years
  resources :benefits do
    collection do
      post 'import'
    end
  end
  resources :products
  resources :contracts do
    collection do
      post 'import'
    end
  end
  resources :deployments do
    collection do
      post 'import'
    end
  end
  resources :portfolios
  resources :people
  resources :organisations
  resources :users
  resources :departments

  get '/about' => 'info#about', as: :about

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#handle_failure'

  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout

  root 'contracts#index'

end

app/models/benefit_year.rb
class BenefitYear < ActiveRecord::Base
  belongs_to :benefit
  default_scope { order(:fy_end_date)}

  monetize :target_value_cents, :allow_nil => true

  def value
    target_value_cents
  end
end

app/controllers/benefit_years_controller.rb
class BenefitYearsController < ApplicationController
  before_action :set_benefit_year, only: [:show, :edit, :update, :destroy]

  # GET /benefit_years
  # GET /benefit_years.json
  def index
    @benefit_years = BenefitYear.all
  end

  # GET /benefit_years/1
  # GET /benefit_years/1.json
  def show
  end

  # GET /benefit_years/new
  def new
    @benefit_year = BenefitYear.new
  end

  # GET /benefit_years/1/edit
  def edit
  end

  # POST /benefit_years
  # POST /benefit_years.json
  def create
    @benefit_year = BenefitYear.new(benefit_year_params)

    respond_to do |format|
      if @benefit_year.save
        format.html { redirect_to @benefit_year, notice: 'Benefit year was successfully created.' }
        format.json { render :show, status: :created, location: @benefit_year }
      else
        format.html { render :new }
        format.json { render json: @benefit_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benefit_years/1
  # PATCH/PUT /benefit_years/1.json
  def update
    respond_to do |format|
      if @benefit_year.update(benefit_year_params)
        format.html { redirect_to @benefit_year, notice: 'Benefit year was successfully updated.' }
        format.json { render :show, status: :ok, location: @benefit_year }
      else
        format.html { render :edit }
        format.json { render json: @benefit_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benefit_years/1
  # DELETE /benefit_years/1.json
  def destroy
    @benefit_year.destroy
    respond_to do |format|
      format.html { redirect_to benefit_years_url, notice: 'Benefit year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benefit_year
      @benefit_year = BenefitYear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def benefit_year_params
      params.require(:benefit_year).permit(:fy_end_date, :target_amount, :benefit_id)
    end
end

app/helpers/benefit_years_helper.rb
module BenefitYearsHelper
end

app/views/benefit_years/_form.html.slim
= form_for(@benefit_year, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @benefit_year.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@benefit_year.errors.count,"error")} prohibited this benefit_year from being saved:"
      ul
        - @benefit_year.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :fy_end_date, class: "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :fy_end_date, class: "form-control"
  .form-group
    = f.label :target_amount, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :target_amount, class: "form-control"
  .form-group
    = f.label :benefit, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :benefit, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/benefit_years/edit.html.slim
.page-header
  = link_to benefit_years_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @benefit_year, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | benefit_year

= render 'form'

app/views/benefit_years/index.html.slim
.page-header
  = link_to new_benefit_year_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Benefit year
  h1
    | Listing benefit_years

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Fy end date
        th
          | Target amount
        th
          | Benefit
        th
        th
        th
    tbody
      - @benefit_years.each do | benefit_year |
        tr
          td
            = benefit_year.fy_end_date
          td
            = benefit_year.target_amount
          td
            = benefit_year.benefit
          td
            = link_to 'Show', benefit_year
          td
            = link_to 'Edit', edit_benefit_year_path(benefit_year) 
          td
            = link_to 'Destroy', benefit_year, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/benefit_years/new.html.slim
.page-header
  = link_to benefit_years_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | benefit_year

= render 'form'

app/views/benefit_years/show.html.slim
.page-header
  = link_to benefit_years_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_benefit_year_path(@benefit_year), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show benefit_year
dl.dl-horizontal
  dt
    | Fy end date:
  dd
    = @benefit_year.fy_end_date
  dt
    | Target amount:
  dd
    = @benefit_year.target_amount
  dt
    | Benefit:
  dd
    = @benefit_year.benefit