config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :benefit_years
  resources :benefits do
    collection do
      post 'import'
    end
  end
  resources :products
  resources :contracts do
    collection do
      post 'import'
    end
  end
  resources :deployments do
    collection do
      post 'import'
    end
  end
  resources :portfolios
  resources :people
  resources :organisations
  resources :users
  resources :departments

  get '/about' => 'info#about', as: :about

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#handle_failure'

  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout

  root 'contracts#index'

end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :position, :color, :description)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.slim
= form_for(@state, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @state.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@state.errors.count,"error")} prohibited this state from being saved:"
      ul
        - @state.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :color, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :color, class: "form-control"
  /
    .form-group
      = f.label :position, class: "col-sm-2 control-label"
      .col-sm-10
        = f.number_field :position, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      p = f.submit class: "button btn-primary"
      p = link_to 'Cancel', "javascript: history.go(-1)"
      p = link_to 'Destroy', @state, method: :delete, data: { confirm: 'Are you sure?' }, class: "button danger"

app/views/states/edit.html.slim
.page-header
  = link_to states_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @state, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | state

= render 'form'

app/views/states/index.html.slim
.pull-right
  = link_to "New", new_state_path, class: 'button btn-primary'
h1 Benefit states
.clear

      - @states.each do | state |
        .state  
          p =link_to state.name, edit_state_path(state)
        p = state.description

app/views/states/new.html.slim
.page-header
  = link_to states_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | state

= render 'form'

app/views/states/show.html.slim
.page-header
  = link_to states_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_state_path(@state), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show state
dl.dl-horizontal
  dt
    | Name:
  dd
    = @state.name
  dt
    | Position:
  dd
    = @state.position
  dt
    | Description:
  dd
    = @state.description