config/routes.rb
Rails.application.routes.draw do
  resources :states
  resources :benefit_years
  resources :benefits do
    collection do
      post 'import'
    end
  end
  resources :products
  resources :contracts do
    collection do
      post 'import'
    end
  end
  resources :deployments do
    collection do
      post 'import'
    end
  end
  resources :portfolios
  resources :people
  resources :organisations
  resources :users
  resources :departments

  get '/about' => 'info#about', as: :about

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#handle_failure'

  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout

  root 'contracts#index'

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/about.html.slim
h1 About this tool
p.lead This is a simple application to view Management Information about Common Technology Services. Over time it may include such things as delivery schedules, benefits realised, current engagement, products in development, etc.

app/views/info/index.html.slim
h1.heading-xlarge CTS Benefits Dashboard
-if !signed_in?
  h2 NOTE: Please speak to Peter Kappus to request an account.
  p.lead If you already have an account, please sign in below.
  = link_to "Sign in", "/auth/google_oauth2", :class=>"button button-start"
-else
  p.lead This tool provides a view of unique benefits being delivered by each product through deployment into various departments. 
  .grid-row
    .column-third
      h2 =link_to "#{Product.all.count} Products", products_path
      p Benefits by product
    /.column-third
      h2 =link_to "#{Contract.all.count} Contracts", contracts_path
      p Data on expiring contracts currently known to CTS.
    .column-third
      h2 =link_to "#{Benefit.all.count} Unique Benefits", benefits_path
      p Benefits information.
    .column-third
      h2 =link_to "#{Department.all.count} Departments", departments_path
      p A list of departments and associated benefits.